### ISSUE TITLE
Internal error when searching `states:nutrition-photo-selected`

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/search-a-licious#253]
### What

When searching `states:nutrition-photo-selected`, an HTTP 500 is returned, due to this exception:

```
INFO:     172.23.0.8:54214 - "GET /autocomplete?q=states:nutrition-photo-selected%20AND%20states:nutrition&lang=fr&taxonomy_names=brands,categories&size=5 HTTP/1.0" 200 OK
2024-10-24 08:55:42,713 :: DEBUG :: Received search query: q='states:nutrition-photo-selected', langs='{'fr'}', page=1, page_size=24, fields='None', sort_by='None', charts='[DistributionChart(chart_type='DistributionChart', field='nutrition_grades'), DistributionChart(chart_type='DistributionChart', field='ecoscore_grade'), DistributionChart(chart_type='DistributionChart', field='nova_groups'), ScatterChart(chart_type='ScatterChart', x='nutriscore_score', y='nutriments.fiber_100g')]'
INFO:     172.23.0.8:54216 - "GET /search?boost_phrase=true&charts=nutrition_grades%2Cecoscore_grade%2Cnova_groups%2Cnutriscore_score%3Anutriments.fiber_100g&facets=brands%2Ccategories%2Cnutrition_grades%2Cecoscore_grade&langs=fr&page=1&page_size=24&q=states%3Anutrition-photo-selected HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/search/app/api.py", line 135, in search_get
    result = app_search.search(search_parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/search/app/search.py", line 82, in search
    query = build_search_query(
            ^^^^^^^^^^^^^^^^^^^
  File "/opt/search/app/query.py", line 268, in build_search_query
    check_query(params, analysis)
  File "/opt/search/app/query.py", line 231, in check_query
    raise QueryCheckError("Found errors while checking query", errors=errors)
app.exceptions.QueryCheckError: Found errors while checking query: 
 - Invalid characters in term value: nutrition-photo-selected
 ```

The backend should not return HTTP 500 even if the user provides an invalid lucene query.

**Comment by CallMeJess** [comment]
Still reproducible on **production** (`search.openfoodfacts.org`) as of **2026-07-29**, ~21 months on. Some extra findings while investigating a different problem — the bug is broader than `states`, and the trigger is narrower than it looks.

**It is not specific to `states`.** `categories` and `labels` return the same 500:

```bash
# 4/4 HTTP 500
curl -sG https://search.openfoodfacts.org/search --data-urlencode 'q=categories:"en:breakfast-cereals"'
curl -sG https://search.openfoodfacts.org/search --data-urlencode 'q=labels:"en:organic"'
curl -sG https://search.openfoodfacts.org/search --data-urlencode 'q=categories:breakfast-cereals'

# 4/4 HTTP 200
curl -sG https://search.openfoodfacts.org/search --data-urlencode 'q=categories:en:breakfast-cereals'
curl -sG https://search.openfoodfacts.org/search --data-urlencode 'q=categories_tags:"en:breakfast-cereals"'
```

**What discriminates a 500 from a 200** — each run twice, all consistent:

| query | result |
|---|---|
| `categories:"en:breakfast-cereals"` | **500** |
| `labels:"en:organic"` | **500** |
| `categories:breakfast-cereals` | **500** |
| `categories:en:breakfast-cereals` (unquoted, `lang:id` form) | 200 |
| `brands:"nestle"` | 200 |
| `allergens:"en:milk"` | 200 |
| `countries:"en:canada"` | 200 |
| `states:"en:to-be-completed"` | 200 |
| `ingredients:"en:sugar"` | 200 |

Two things stand out from that table:

1. **`states:"en:to-be-completed"` returns 200** while this issue's `states:nutrition-photo-selected` returns 500 — so the failing input is the value that still needs taxonomy *resolution* (a bare term, or a quoted phrase), not the field. Giving an already-resolved, unquoted `lang:id` token succeeds.
2. The three fields I could make fail — `categories`, `labels`, `states` — are hit whenever the value needs resolving, whereas `allergens` / `countries` / `ingredients` accept the same quoted `en:` form happily. I couldn't get `brands` to fail at all. I don't know the mechanism, so treat the grouping as an observation rather than a diagnosis; the `full_text_search: true` flag correlates for `categories`/`labels` but not for `states`, so that alone doesn't explain it.

**Practical impact for reusers:** the taxonomy-mapped fields are what the config and docs present as the query surface, and the only reliable path today is the raw `*_tags` fields. A caller following the documented field name gets a 500 with no hint that a different spelling works.

Worth noting that this and #437 (the `conutries_tags` typo) are separate causes with the same symptom class — between them, **all four** documented taxonomy query surfaces I tried either 500 or silently return nothing.
